In [10]:
import numpy as np

M = np.array([[29.36,51.23,78.3],[45.44,33.2,32.5],[25.2,81.5,13.35]])

print(M)

[[29.36 51.23 78.3 ]
 [45.44 33.2  32.5 ]
 [25.2  81.5  13.35]]


In [11]:
total= M.sum(axis=0)
print(total)

[100.   165.93 124.15]


In [15]:
TM = total.reshape(1,3)
print(TM)

[[100.   165.93 124.15]]


In [18]:
percentage = 100*M/TM
print(percentage)

[[29.36       30.87446514 63.0688683 ]
 [45.44       20.00843729 26.17801047]
 [25.2        49.11709757 10.75312122]]


In [19]:
percentage = percentage - 100
print(percentage)

[[-70.64       -69.12553486 -36.9311317 ]
 [-54.56       -79.99156271 -73.82198953]
 [-74.8        -50.88290243 -89.24687878]]


In [20]:
percentage = percentage + np.array([100, 200, 300])
print(percentage)

[[ 29.36       130.87446514 263.0688683 ]
 [ 45.44       120.00843729 226.17801047]
 [ 25.2        149.11709757 210.75312122]]


In [22]:
percentage = percentage + np.array([[100],[200],[300]])
print(percentage)

[[129.36       230.87446514 363.0688683 ]
 [245.44       320.00843729 426.17801047]
 [325.2        449.11709757 510.75312122]]
